CREATE DATABASE IF NOT EXISTS dinedrop CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE dinedrop;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;